solon.extend: "waterraas_ext"

server.port: 9375

solon.app:
  name: "waterraas"
  group: "water"

solon.cloud.water:
  server: "waterapi:9371"
  log:
    default: "water_log_raas"
  event:
    seal: "qTYzsNjzCN9I44FB"

solon.logging.appender:
  console:
    level: "INFO"

solon.logging.logger:
  "org.eclipse.jetty.*":
    level: "WARN"
  "com.zaxxer.hikari.*":
    level: "WARN"
