solon.extend: "rubberapi_ext"

server.port: 9262

solon.app:
  group: "water"
  name: "rubber-api"

solon.cloud.water:
  server: "waterapi:9371"
  event:
    seal: "kPbb5KWi2FzPbA43"

solon.logging.appender:
  console:
    level: "INFO"

solon.logging.logger:
  "org.eclipse.jetty.*":
    level: "WARN"
  "com.zaxxer.hikari.*":
    level: "WARN"
