solon.extend: "rubber_ext"

server.port: 9375

solon.app:
  name: "rubber-api"
  group: "rubber"

solon.cloud.water:
  server: "waterapi:9371"
  event:
    seal: "EPscAInrdcEXhm8X"

solon.logging.appender:
  console:
    level: "INFO"

solon.logging.logger:
  "org.eclipse.jetty.*":
    level: "WARN"
  "com.zaxxer.hikari.*":
    level: "WARN"
