solon.extend: "rubberadmin_ext"

server.port: 9261
server.session.timeout: 360000 #10h

solon.app:
  group: "rubber"
  name: "rubber-admin"
  title: "RUBBER"

solon.cloud.water:
  server: "waterapi:9371"
  event:
    seal: "fh9XvMEV8H3Yi8ov"
  config:
    load: "grit:grit.yml,grit:gritclient.yml"

solon.logging.appender:
  console:
    level: "INFO"

solon.logging.logger:
  "org.eclipse.jetty.*":
    level: "WARN"
  "com.zaxxer.hikari.*":
    level: "WARN"


waterfaas.secretKey: "0zJt0J88TkIvqYgC"
